### ISSUE TITLE
python tests.py fails

### ISSUE THREAD

**Issue by rwillmer** [django-behave/django-behave#41]
Our webpage says 'You can run all unittest2 tests with the following: python tests.py'

https://github.com/django-behave/django-behave

This fails with 

Air:django-behave rachel$ ve/bin/python tests.py 
F.FF
======================================================================
FAIL: test_runner_with_default_args_expect_bdd_tests_run (__main__.BehaveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 30, in test_runner_with_default_args_expect_bdd_tests_run
    self.assertIn('scenario passed', actual.out)
AssertionError: 'scenario passed' not found in ''

======================================================================
FAIL: test_runner_with_old_tag_specified_expect_only_old_bdd_test_run (__main__.BehaveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 40, in test_runner_with_old_tag_specified_expect_only_old_bdd_test_run
    self.assertIn('1 scenario passed, 0 failed, 1 skipped', actual.out)
AssertionError: '1 scenario passed, 0 failed, 1 skipped' not found in ''

======================================================================
FAIL: test_runner_with_undefined_steps_expect_display_undefined_steps (__main__.BehaveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 45, in test_runner_with_undefined_steps_expect_display_undefined_steps
    self.assertIn('You can implement step definitions for undefined steps with', actual.err)
AssertionError: 'You can implement step definitions for undefined steps with' not found in 'Traceback (most recent call last):\n  File "./manage.py", line 8, in <module>\n    from django.core.management import execute_from_command_line\nImportError: No module named django.core.management\n'

----------------------------------------------------------------------
Ran 4 tests in 0.201s

FAILED (failures=3)

**Comment by rwillmer** [comment]
You get this if you run without activating the virtualenv if you're using one. I'll update the doco to mention that :)

**Comment by galuszkak** [comment]
I assume that with activated virtualenv everything is working fine right?

**Comment by rwillmer** [comment]
Yep, works fine. Stupid user error :)
