### ISSUE TITLE
Django 1.8 compatibility

### ISSUE THREAD

**Issue by tsouvarev** [django-behave/django-behave#44]
When running tests, I get the following exception:
```
$ ./manage.py test
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/minime/.virtualenvs/kohanka/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/minime/.virtualenvs/kohanka/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/minime/.virtualenvs/kohanka/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/minime/.virtualenvs/kohanka/lib/python3.4/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/minime/.virtualenvs/kohanka/lib/python3.4/site-packages/django/core/management/base.py", line 351, in create_parser
    self.add_arguments(parser)
  File "/home/minime/.virtualenvs/kohanka/lib/python3.4/site-packages/django/core/management/commands/test.py", line 57, in add_arguments
    "The method to extend accepted command-line arguments by the "

RuntimeError: The method to extend accepted command-line arguments by the test management command has changed in Django 1.8. Please create an add_arguments class method to achieve this.
```

**Comment by tsouvarev** [comment]
Turns out, if you add this method to class DjangoBehaveTestSuiteRunner, that solves the problem 
```
    @classmethod
    def add_arguments(cls, parser):
        # Set up to accept all of Behave's command line options and our own.  In
        # order to NOT conflict with Django's test command, we'll start all options
        # with the prefix "--behave_" (we'll only do the long version of an option).
        option_list, cls.option_info = get_options()

        for option in option_list:
            parser.add_argument(*option._long_opts, action=option.action, dest=option.dest, help=option.help)
```

**Comment by maccesch** [comment]
It would be awesome if you could push this to your repo, so I could install it from there. Thanks!

**Comment by mixxorz** [comment]
You could check out [behave-django](https://github.com/mixxorz/behave-django). It's an alternative to django-behave for integrating behave BDD tests for Django. I personally think it's better, but that might just be because I made it :stuck_out_tongue:

**Comment by rwillmer** [comment]
If you make a Pull Request which passes the Travis CI test, I'll merge and release it

**Comment by maccesch** [comment]
@rwillmer Nice to see that you continue to support django-behave

@mixxorz behave-django looks nice but it is lacking documentation. How do I set up splinter as context.browser? How do I load a fixture before running my tests?

**Comment by mixxorz** [comment]
@maccesch Oh. You can post your questions about behave-django on its issue tracker. I'd love to get some feedback. :grinning: 

To answer your question though, I think you're right. I guess it does lack documentation. I'll go ahead and write some use cases. Thanks.

**Comment by rwillmer** [comment]
Just uploaded v0.1.4 to pypi with the Django 1.8 PR, let me know of any problems.

Please close this ticket if it's now working for you :)

**Comment by maccesch** [comment]
Works perfectly. Thanks!

**Comment by maccesch** [comment]
Works for me, thanks!

**Comment by rwillmer** [comment]
@maccesch I'm happy to merge PRs which pass the Travis CI; not actively using django-behave myself at the moment, so I can't contribute any time towards changes sadly.

@tsouvarev does this work for you now? please close the issue if so

**Comment by tsouvarev** [comment]
@rwillmer right now I cant check that, so I will just close issue
