### ISSUE TITLE
runner not testing most apps Django 1.8

### ISSUE THREAD

**Issue by lukeaus** [django-behave/django-behave#67]
Was using django-behave==0.1.5 and behave==1.2.5 and Django 1.7 without issue.

Upgraded to Django 1.8 and all non behave tests run from all apps, but behave tests only run for the first listed app.

e.g. 
./manage.py test foo bar baz

all django unit/system tests run for foo and bar and baz
but behave tests only run for foo, not bar  or baz (or any subsequent apps)

happens with using:
TEST_RUNNER = 'django_behave.runner.DjangoBehaveTestSuiteRunner'
and with using:
TEST_RUNNER = 'django_behave.runner.DjangoBehaveOnlyTestSuiteRunner'

I have spent a few hours on this today and can't work out what is going on.

Any help would be greatly appreciated.

Thanks

**Comment by lukeaus** [comment]
I think this is an issue with django, particularly with
partition_suite function in django.test.runner
I will post on django issue tracker

**Comment by lukeaus** [comment]
Turns out this was due to django implementing OrderedSet where there was not previously. 
More info here
https://code.djangoproject.com/ticket/26198#comment:2

**Comment by rwillmer** [comment]
Thanks Luke
